.TH ws 1 "October 2025" "2.5" "User Commands"
.SH NAME
ws - afficher des animations de bateaux
.SH SYNOPSIS
.B ws
[\-W] [\-l]
.SH DESCRIPTION
La commande \fBws\fR affiche des animations ascii de bateaux dans le terminal. 
Inspiré par la la commande sl.
.SH OPTIONS
.TP
.B \-W
Affiche le cuirassé Wisconsin.
.TP
.B \-l
Affiche un petit bateau.
.SH EXAMPLES
.B ws
Affiche le cuirassé Alsace par défaut.
.TP
.B ws \-W
Affiche le cuirassé Wisconsin.
.TP
.B ws \-l
Affiche un petit bateau
.SH AUTHOR 
Crée par Yann STOLL-GEYER <yann.stoll-geyer@etu.unistra.fr>
.TP
Inspiré par le commande \fBsl\fR écrite par Toyoda Masashi (mtoyoda@acm.org)
.SH SEE ALSO
sl(1)

